import React from "react";
import { Seo } from "../components/seo";
import { Link } from "gatsby";
import Layout from "../components/layout";
import ContentWidth from "../components/contentWidth";
import AI_family from "../images/family/AI-family.png";

const FamilyPage = () => {
  return (
    <Layout>
      <ContentWidth>
        <section className="row">
          <div className="column">
            <h1>Family</h1>
            <p>
              <em>
                Family. There's nothing quite like it. A collection of people
                closely connected by genetics, name, home life, and all manner
                of endearing eccentricities.
              </em>
            </p>
            <p>
              <em>
                So much else can and often does change in life, but family
                remains, well, family. We share moments of joy, sadness,
                excitement, and cake.
              </em>
            </p>
            <p>
              <em>
                My wonderful wife and two amazing daughters mean everything to
                me. They're my fellow adventurers in life — and they continue to
                surprise, delight, inspire, confuse, and amuse me.
              </em>
            </p>
            <p>
              <em>Here's to family!</em>
            </p>
            <p>&nbsp;</p>
            <p>
              Also very much part of the family is{" "}
              <Link to="/dog">our dog</Link>, Tiffin.
            </p>
          </div>
          <div className="column">
            <img
              alt="A family standing with their dog, generated by AI (not my actual family)"
              className="block tilt-portrait-left do-not-print"
              src={AI_family}
            />
            <p className="caption-text-family">
              An AI-generated image of a mum, dad, two daughters, and a dog.
            </p>
          </div>
        </section>

      </ContentWidth>
    </Layout>
  );
};

export default FamilyPage;

export const Head = () => (
  <Seo
    description="A brief page about Tom Waterton's family — his wife, two daughters, and their dog Tiffin."
    title="Family – Tom Waterton"
  />
);
